### ISSUE TITLE
Add bspwm setup

### ISSUE THREAD

**Issue by A-Siam** [sagb/alttab#109]
my tested setup on my system hope you add it to your doc

 WM/DE       | best value for `-w` option  | how to release grabbed Alt-Tab | autostart
------------ | --------------------------- | ------------------------------ | ---------
bspwm        | 1 (set manually)            | doesn't grab                   | `alttab &` in ~/.config/bspwm/bspwmrc

**Comment by devins2518** [comment]
Can confirm. Without setting `-w 1` manually, it shows all nodes and its possible to kill the window manager. I would add that I needed to add `alttab -w 1 &` explicitly in my autostart to fix this behavior.

**Comment by A-Siam** [comment]
I found they didn't add it for nowm so I decide to keep it consistent, however, I totally agree with you it is more convenient to just copy and paste what works

**Comment by sagb** [comment]
I start alttab under bspwm and it recognises WM correctly:

> alttab -v  
> ...
> EWMH-compatible WM detected: bspwm  
> WM: 1  

Perhaps bspwm executes bspwmrc before initializing EWMH hints? You could check it by changing `alttab &` to something like `sh -c "sleep 10 ; alttab &"` in bspwmrc.

**Comment by A-Siam** [comment]
@sagb It worked indeed i was just suggesting adding it to the doc and thought it is not PR worthy

**Comment by sagb** [comment]
So, I suppose autorecognition works. I've mentioned bspwm in docs, thank you.

**Comment by A-Siam** [comment]
> So, I suppose autorecognition works. I've mentioned bspwm in docs, thank you.

You are welcome. We have to set `-w 1` manually, it doesn't detect that option by default.

**Comment by sagb** [comment]
You can perform some diagnostics: https://github.com/sagb/alttab/issues/109#issuecomment-751364685

**Comment by A-Siam** [comment]
@sagb  Sorry for the late response, what kind of diagnostics you want me to do?

**Comment by sagb** [comment]
I mean, perhaps bspwm executes bspwmrc too early, before initializing EWMH hints? You could check it by changing alttab & to something like sh -c "sleep 10 ; alttab &" in bspwmrc.
