### ISSUE TITLE
AltTab connects to appcenter.ms?

### ISSUE THREAD

**Issue by JayBrown** [sagb/alttab#110]
Why is AltTab connection to the Microsoft domain appcenter.ms?

In the Info.plist it says that is an "AppCenterApplication". (?)

**Comment by sagb** [comment]
This is absolutely impossible, you are wrong.

**Comment by sagb** [comment]
Perhaps some shared library used by alttab does this in your system?

**Comment by JayBrown** [comment]
Sorry, wrong repo. This should have gone into alt-tab-macos.
