### ISSUE TITLE
Scratchpad window still showing

### ISSUE THREAD

**Issue by krzkrzkrz** [sagb/alttab#111]
Using Bspwm. In `.config/bspwm/bspwmrc`, I have:

```
alttab -w 1 -d 2 -frame rgb:26/8b/d2 -bg rgb:f1/f1/f1 -fg rgb:55/55/55 -t 120x120 -i 120x120 &
```

`ps aux | grep alttab`, returns:

```
user1    1153393  0.0  0.0  17780 13324 ?        S    Jan26   0:13 alttab -w 1 -d 2 -frame rgb:26/8b/d2 -bg rgb:f1/f1/f1 -fg rgb:55/55/55 -t 120x120 -i 120x120
```

`man alttab` mentions the following:

```
2: All desktops, excluding special (-1) one.

In various EWMH WM this desktop may be designed hidden or containing sticky windows. In i3, it's "scratchpad".
```

On Bspwm, I have a scratchpad window running (via kitty). `ps aux | grep kitty`, returns:

```
user1    1122096  0.0  0.2 537712 88472 ?        Sl   22:00   0:00 kitty --class scratchpad -e /home/user1/.scripts/bspwm/tmux
```

However, alttab stil shows the scratchpad window. The expected result is, alttab, should not show thee scratchpad window.

**Comment by sagb** [comment]
Please see https://github.com/baskerville/bspwm/issues/1256.
Unlike some WMs, there is no scratchpad in bspwm, so there is nothing to recognize in alttab.
You implement your "scratrchpad" and so you should probably take care of skipping it in task switchers. Specifically, you can set standard _NET_WM_STATE_SKIP_TASKBAR property on kitty window, and then alttab will skip it.
Like:
> wmctrl -x -r scratchpad -b add,skip_taskbar

(not tested)
