### ISSUE TITLE
Fluxbox Alttab показывает службы запущенные в фоне (Fluxbox Alttab  shows the services running in the background)

### ISSUE THREAD

**Issue by sws33** [sagb/alttab#112]
Если alttab запустить после загрузки всей системы в терминале, то всё нормально, если его запускать через fluxbox autostart-file (см. ниже):
```
alttab &
exec fluxbox
```
то показывает все службы, запущенные в фоне. Как это пофиксить? :)

Тестировал на последней версии, скомпилированной из исходников 1.6.0

Translate:

If you run alttab after loading the entire system in the terminal, then everything is fine if you run it via the fluxbox autostart-file (see below):
```
alttab &
exec fluxbox
```
it shows all the services running in the background. How to fix it? :)

Tested on the latest version compiled from source 1.6.0

**Comment by sws33** [comment]
Всё, разобрался! - https://github.com/sagb/alttab/blob/master/doc/wm-setup.md :)

**Comment by sagb** [comment]
Affirmative.
