### ISSUE TITLE
Feature request: kill window

### ISSUE THREAD

**Issue by eater** [sagb/alttab#113]
It would be great to have a key command to send a kill signal to the selected window. So the user could hold down `Alt`, tap `Tab Tab Tab`, then, still holding down `Alt`, tap `Q` to kill that window. (Then `Tab Tab Q` to kill another, etc.)

Use case: Right now I have 90 PDFs open and I just want to get rid of the unnecessary windows quickly.

**Comment by sagb** [comment]
Implemented: by pressing "k" or another key specified via `-dk`, alttab will the kill X client to which currently selected window belongs. The corresponding tile is filled blank.
