### ISSUE TITLE
Crash if started with -i or -t set to 0x0

### ISSUE THREAD

**Issue by zneix** [sagb/alttab#115]
When you start alttab with the following: `alttab -i 0x0` or `alttab -t 0x0`, upon pressing Alt+Tab it will crash  
![sigpipe with -i](https://cdn.zneix.eu/eofuXoo.png)
![sigpipe with -t](https://cdn.zneix.eu/0R6fcZ0.png)

Backtrace from gdb doesn't reutrn anything relevant:  
![gdb backtrace](https://cdn.zneix.eu/vUQr7Al.png)

**Comment by sagb** [comment]
The solution will be:
* for `-i 0x0`: error message, die. Instead, implement `-s` option to disable icons at all.
* for `-t 0x0`: error message, die.

It's low priority bug (filtering user input) and low priority enhancement (disable icons), but should be fixed sometime.
