### ISSUE TITLE
Feature request: Immediate switch and no visual queue

### ISSUE THREAD

**Issue by elundmark** [sagb/alttab#117]
First off, thank you!
I was hoping this program could have an option to switch immediately, without showing anything at all.
If not, could some kind soul send me a patch for this?

**Comment by sagb** [comment]
I doubt it's viable, too heavy modification would be required.
Simple switch is often implemented in window manager using its own key bindings, search for "next/prev window" for your wm.

**Comment by elundmark** [comment]
Thanks!

On Mon, 05 Jul 2021 05:50:33 -0700
sagb ***@***.***> wrote:

> I doubt it's viable, too heavy modification would be required.
> Simple switch is often implemented in window manager using its own
> key bindings, search for "next/prev window" for your wm.
> 


-- 

PGP? ==> ***@***.***
