### ISSUE TITLE
filter window ?

### ISSUE THREAD

**Issue by wade-fs** [sagb/alttab#118]
I found some app, such as firefox, will create multi-window in alt-tab list, but cannot switch to it.
I guess those windows without available window id.
Could weed out that?

**Comment by sagb** [comment]
Try to guess what's special with that non-focusable windows. You can run `alttab -vv` from terminal, try to switch to problem window and look for correspondent `changing focus to <id>` line in alttab output.
Then examine that window: `xprop -id <id>`

**Comment by sw882882** [comment]
for those who searched and are still having this issue, messing around with the -w option fixed it for me, whether this is intended or not I am not sure.

**Comment by sagb** [comment]
To say something meaninfull, I asked for diagnostics from those who can reproduce this bug. Here is even more detailed step-by-step procedure:
1. Kill alttab if it's running (`killall alttab`)
2. Start alttab from within terminal emulator with `-v` option. It will print diagnostics to standard output during run.
3. Try to switch to "non-selectable" window with alttab (let it fail).
4. Switch to terminal where alttab is printing (without using alttab! Probably using mouse).
5. Look for the following lines in diagnostic output: `changing focus to ...`. Window id will be mentioned here (0x12345...)
6. Either kill alttab (ctrl-c) or start another terminal session, and run: `xprop -id 0x12345`, where `0x12345` is obtained in previous step. Show the output in this github issue.
7. Also, show the output of `alttab -v 2>&1 | grep WM` and what WM are you actually running.
