### ISSUE TITLE
Open alttab-window only after a certain delay

### ISSUE THREAD

**Issue by astier** [sagb/alttab#119]
### Problem

I often use alt-tab to switch quickly between the two recently used programs. This mean I press alt-tab only once to switch to the last used window. Since I already now which window this will be I dont want to see the previews of all the windows because it is visually distracting to see a brief flickering of the alttab-window.

### Solution

Many other DEs (Ubuntu, KDE, MacOS) have a delay for their alt-tab-switchers to display the alttab-window only after a certain time (ex. 200ms). It would be nice if alttab would have an option to let the user define a certain delay.

### Example

1. Three windows are open
2. Press alt-tab and release it immediately -> last used window is focused and the alttab-window didn't open
3. Press alt-tab and hold alt -> after a certain delay (ex. 200ms) the alttab-window opens
4. Press alt-tab-tab quickly before the delay is over -> alttab-window opens although the delay isn't over because after pressing tab two times we know that the user didn't want simply to focus the last used window but wants to traverse the opened windows

**Comment by uunnxx** [comment]
Sounds good, I'm in.

**Comment by astier** [comment]
I just discovered that cinnamon also has an option in their settings to specify the delay for their alttab-window.

**Comment by sagb** [comment]
I'm sorry to admit, but existing code is not suitable for this: switching logic is not separated from user interface.
In particular, to disable GUI, we would rewrite and debug again every condition statement in event/timer cycle (main.c:525), which I consider stable and not worth breaking.
