### ISSUE TITLE
ARM Version for Single Board Computer

### ISSUE THREAD

**Issue by GreenLunar** [sagb/alttab#124]
The title says it all (:

**Comment by sagb** [comment]
What exactly is wrong?
According to http://crossqa.debian.net/src/alttab , alttab cross-builds for arm LE and BE and 64bit without any modification.
Also, I built (and used) it with native toolchain for armv7l (Nexus 10 tablet).

**Comment by GreenLunar** [comment]
I'll refer to Arch Linux ARM forum and get back to you. Thanks
