### ISSUE TITLE
is there a way for pywal support?

### ISSUE THREAD

**Issue by autoteelar** [sagb/alttab#125]
pywal grabs colors from your wallpaper and you can do things to make it apply to your terminal, even your system theme with oomox and i3 colors and stuff through config, i was wondering if that would be possible here somehow,

**Comment by sagb** [comment]
Refer to https://github.com/dylanaraps/pywal/wiki/User-Template-Files . There are two possible ways:

1. Make a template for X resources:

> alttab.background: {background}
> alttab.foreground: {foreground}
> alttab.framecolor: {color1}

and load it like:
> xrdb -merge < ~/.cache/wal/alttab
> killall -w alttab
> alttab &

2. Make a template with command line options:

> opt="-bg {background} -fg {foreground} -frame {color1}"

and load it like:
> killall -w alttab
> . ~/.cache/wal/alttab
> alttab $opt

I didn't try.
Don't forget to report your success, so we can include your experience in documentation.

**Comment by autoteelar** [comment]
nice ill try it out and let you know what happens
