### ISSUE TITLE
Is supporting qtile possible?

### ISSUE THREAD

**Issue by OAshkar** [sagb/alttab#127]
Hi,
Thank you for creating this software. I am a qtile user.  [Qtile autostart](http://docs.qtile.org/en/latest/manual/config/hooks.html#autostart.) method is straightforward. However, then I add alttab in that file, random things happens. So, ethier it don't work (probably because alt+tab got reserved some where) or It works with 100 of applications from the tray and xdev which are background processes!

When I run alttab from the environment, I got this message. 

```
alttab: Error while (un)grabbing key 0x17 with mask 0x9/0x12.
Probably other program already grabbed this combination.
Check: xdotool keydown alt+Tab; xdotool key XF86LogGrabInfo; xdotool keyup Tab; sleep 1; xdotool keyup alt
and then look for active device grabs in /var/log/Xorg.0.log
Or try Ctrl-Tab instead of Alt-Tab:  alttab -mk Control_L
```

However that log file mentioned is empty. 

Finally, when I try to make the modifier Control-L, it works perfectly. 

I hope to support qtile as it is a really nice wm.

Thank You

**Comment by sagb** [comment]
Do you use X11 or Wayland?

**Comment by sagb** [comment]
I've installed qtile, and alttab works in it for me without any problem: Alt-Tab keys work, no unwanted windows, even `-d` works.

About your Alt-Tab binding problem: probably your qtile keybinding are not default or some other application grabs Alt-Tab. You could start with default configuration and then add things until they break alttab.

About 100 of application: try either some delay: `sh -c "sleep 5 ; alttab"` or explicitly set the type of window manager: `alttab -w 1`.

**Comment by OAshkar** [comment]
Thank you for your reponse. Maybe it is my configuration problem then. I will close the issue, till I traceback and find where the problem was.

**Comment by aloispichler** [comment]
I am running alttab on qtile. It works well, if there is only one screen.
But with two monitors, the focus always stays on the active screen. I am not able to get the config right to focus the screen. Any suggestions regarding the alttab options? Thanks in advance.

**Comment by sagb** [comment]
Specify what do you mean by "focus always stays on the active screen":
alttab doesn't list all windows?
alttab doesn't show the switcher at expected place?
alttab can't switch to the window after releasing Alt?

**Comment by aloispichler** [comment]
Alttab lists all windows and switches to the window after releasing Alt.
The behavior I have expected is:
* By selecting a window via alttab, that window (and group) should be focused, without moving the group containing the window to the active screen.
Is there perhaps a setting which enables this behavior?
Thanks.
