### ISSUE TITLE
screenshot instead of icon

### ISSUE THREAD

**Issue by aloispichler** [sagb/alttab#135]
I am really happy to have found alttab, using it multiple 1000 times a day.

Unfortunately, the icons on the tiles are the same for multiple terminal instances, e.g., so it is difficult to distinguish the different windows just from the bar displayed by alttab.
It would be nice to have a screenshot instead of the icon:
https://alt-tab-macos.netlify.app/

Thank you!

**Comment by sagb** [comment]
This would require a heavy dependency (composite extensions, AFAIR) and significant rewrite, sorry.
I work around this by setting a window title: xterm -T title

**Comment by LoganDark** [comment]
> This would require a heavy dependency (composite extensions, AFAIR) and significant rewrite, sorry. I work around this by setting a window title: xterm -T title

That's not a true workaround, it just solves the issue of not being able to differentiate multiple windows. My use case is more specific - telling windows apart quickly, without having to read. This is not solved by alttab but the alternative is fluxbox's built-in implementation which is really janky and uncomfortable.
