### ISSUE TITLE
MacOS Ventura Stage Manager Windows Appear Tilted

### ISSUE THREAD

**Issue by sebmandal** [sagb/alttab#148]
The windows in the switcher appear tilted when using Stage Manager. It also seems like this is inconsistent, some that are not open on the current stage appear tilted, whilst some others don't.

In this example VSCode is open on the current stage. Spotify, Beekeper, and Firefox are all on different stages, Spotify appears normal while the others are tilted.
<img width="1097" alt="Screenshot 2023-04-08 at 16 16 19" src="https://user-images.githubusercontent.com/68667029/230726091-c0ed251c-fa65-42f7-8a62-10404dd3f05e.png">

**Comment by sagb** [comment]
These screenshots are unrelated to this repository. `Alttab` is a standalone program, not a standard macos task switcher.
