### ISSUE TITLE
xterm mini-window has no icon

### ISSUE THREAD

**Issue by bart0101** [sagb/alttab#15]
in evilwm, xterm mini-window has empty icon (just a frame). not very annoying, but why?

**Comment by sagb** [comment]
It's because xterm doesn't provide icon_pixmap member in WM hints, while alttab doesn't search for icon in any other place than this. This is planned enhancement, see #13.

**Comment by bart0101** [comment]
Oh well.
Great program though, thank you.

**Comment by sagb** [comment]
Closed in v1.1.0
