### ISSUE TITLE
X11

### ISSUE THREAD

**Issue by aloispichler** [sagb/alttab#150]
alttab is X11 window switcher …
Does alttab work with wayland?
Thanks

**Comment by sagb** [comment]
No.

**Comment by aloispichler** [comment]
Any plans for wayland? Or a recommendation for a similar switcher in wayland?

**Comment by sagb** [comment]
Alttab will never work in Wayland, because it depends heavily on X11 for everything.

**Comment by sagb** [comment]
Typical software uses toolkit like gtk and can be ported to Wayland. Alttab is not typical software: it's based on dosen of low-level features, every one of them has very specific interface in X11: error handling, keyboard grab, event polling loop, monitoring window properties change, selecting windows to show, extracting name, setting focus, multi-monitor support. If you write it for Wayland, it will be completely different program, you will rewrite it from scratch.

**Comment by itsjfx** [comment]
For those moving to sway, I made this to fill the gap. Only sway is supported and it's not as customisable as alttab, but the experience should be familiar https://github.com/itsjfx/sway-alttab-gui
