### ISSUE TITLE
Unclear -d option usage

### ISSUE THREAD

**Issue by jidanni** [sagb/alttab#156]
On https://github.com/i3/i3/discussions/5886 I show how there is not enough documentation for slower learning users like me to be able to use the "alttab" program. Yes, the man page also assumes advanced knowledge.

**Comment by sagb** [comment]
Alttab *is* designed to start as simple as just `alttab`.
Please learn to report bugs. There is thorough recommendations from GNU, but I find [this short guide](https://archaeogeek.github.io/foss4gukdontbeafraid/bugs/index.html) very good.
Attach screenshots of your problem.
Read man page! Provide information about your desktops, try to change `-d` option.

Delete unprofessional complains in non-related i3 repository.

**Comment by jidanni** [comment]
Okay, when I get back to town next week I'll post what I saw on my screen. Thanks.

**Comment by jidanni** [comment]
Here you can see I have according to
/usr/share/doc/alttab/wm-setup.md.gz
I have altered my i3 config file as so,
```
#bindsym $mod+Tab workspace back_and_forth
exec_always alttab
```
The result is **only one choice**.
![20240203T144600](https://github.com/sagb/alttab/assets/1230959/e87827f9-f9a5-4050-9e2a-7db7e9f55c89)

On the bottom of the screen you see I have gone to the Uxterm window
to execute
```
import -window root -pause 13 pic.jpg
```
and during those 13 seconds I went back to the emacs window to do
alt+tab which only shows one choice.

In fact the only time I got it to show two choices is when I do
xli image.jpg&
then I get two choices, the shell, and xli.

Anyway, I expect to see three choices, just like the row at the bottom
of the screen: SU, uxterm, and Emacs.

Even after doing `service lightdm restart`, each window only shows one
choice when alt+tab is pressed.

SU when in the SU window,
uxterm when in the uxterm window,
and Emacs when in the Emacs window.

So to switch windows I have to fall back to ALT+number.

Package: alttab
Version: 1.7.1-1
System Information:
Debian Release: trixie/sid
Architecture: amd64 (x86_64)

Kernel: Linux 6.6.13-amd64 (SMP w/4 CPU threads; PREEMPT)
Locale: LANG=zh_TW.UTF-8, LC_CTYPE=zh_TW.UTF-8 (charmap=UTF-8), LANGUAGE=en_US:en
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages alttab depends on:
ii  libc6        2.37-15
ii  libpng16-16  1.6.42-1
ii  libx11-6     2:1.8.7-1
ii  libxft2      2.3.6-1
ii  libxpm4      1:3.5.17-1
ii  libxrandr2   2:1.5.2-2+b1
ii  libxrender1  1:0.9.10-1.1

**Comment by orestisfl** [comment]
> Anyway, I expect to see three choices, just like the row at the bottom of the screen: SU, uxterm, and Emacs.

Use `alttab -w 1 -d 1` to show windows across different workspaces.

**Comment by jidanni** [comment]
> alttab -w 1 -d 1

Ah! no wonder!

(I have an idea, perhaps make the default be -d 1 instead of -d 0.
That way dumber users would still find all their windows, and smarter users could customize it  back to -d 0.)

**Comment by sagb** [comment]
When a user has 50 windows open across various workspaces and then launches alttab for the first time, the default display of all these windows would be so ugly, to the point where the user may not even bother to find out if alttab can show fewer windows.
On the contrary, if the user is presented with windows from only one desktop (as in your scenario), they are more likely to understand how it works (just as you did).
That's why `-d 0` is default.

**Comment by sagb** [comment]
To understand, view the screenshot here (despite the fact that it turned out this way for a different reason): https://github.com/sagb/alttab/issues/152

**Comment by jidanni** [comment]
Hmmm, maybe have an additional choice, not just one or all.
Perhaps "a few" and have the exact limit chosen by another variable...
