### ISSUE TITLE
Just  show whole tab while user is picking which tab to choose

### ISSUE THREAD

**Issue by jidanni** [sagb/alttab#158]
I have an idea for alttab:

For the row of boxes in the middle of the screen, instead of looking
at the icons and having to *think* which tab they represent (yes,
despite icons and names present,) have actual "most recent thumbnail snapshots"
of each tab. Sure, with the icon overlayed on them. Chromebooks do similar tab switching.

Or better yet, no boxes in the middle of the screen. Instead we just
(appear to temporarily) simply switch to the tab and if that's the one
we want we could then release our fingers, and if it's not then we
just keep on hitting TAB (while holding ALT), until we get to the one
we want.

When we release our fingers at the desired tab, nothing should happen
(because we are already looking at our desired tab,) except that
perhaps some overlayed icon in the corner could disappear.

By the way, our eyeballs are fixed on this bar on the bottom (of i3),
![20240205T080544](https://github.com/sagb/alttab/assets/1230959/2138ffc7-5e12-49f0-8d6d-d4547450e711)
Could there somehow be some coordination so that we also see those
blocks change their colors while we are still switching,
just like if we had finally released our fingers?

**Comment by sagb** [comment]
Idea of preview was already discussed in https://github.com/sagb/alttab/issues/106, https://github.com/sagb/alttab/issues/135, https://github.com/sagb/alttab/issues/140, it's not feasible.

Idea of "simply" switch as well as tinkering with the i3 taskbar, are even less practical. These approaches introduce dependencies on the window manager and are not in line with the nature of alttab as a simple switcher.
