### ISSUE TITLE
alttab man page on OpenBSD should go to other dir

### ISSUE THREAD

**Issue by Veraellyunjie** [sagb/alttab#162]
On OpenBSD, manpages of software from ports/packages go into `/usr/local/man`, so full path would be
not `/usr/local/share/man/man1/alttab.1`
but `/usr/local/man/man1/alttab.1`
https://man.openbsd.org/man.conf#EXAMPLES

Sorry, I lack knowledge of `automake` to prepare a pull request

**Comment by sagb** [comment]
If you build alttab manually, then use `--mandir` option of `configure` to specify the path.
If you use pre-packaged port/package, then please submit a bugreport to them.
