### ISSUE TITLE
how can cancel switch item, the issus ,is closed, it not fixed

### ISSUE THREAD

**Issue by newyorkthink** [sagb/alttab#168]

**Comment by sagb** [comment]
1. You don't communicate clearly, violating Github Usage Guidelines and probably their TOS and AUP. Try using Google Translate.

2. Please learn to report bugs. There are thorough recommendations from GNU, also I find [this short guide](https://archaeogeek.github.io/foss4gukdontbeafraid/bugs/index.html) good enough.
