### ISSUE TITLE
transparency? how?

### ISSUE THREAD

**Issue by darkralts** [sagb/alttab#171]
how did you get the picom rule to work?

    "88:class_g = 'AltTab '", or alttab wont work for me, pls help :3

**Comment by sagb** [comment]
I don't know how to configure picom. Check its documentation.
#137 suggests it can work with alttab, though it's not very handy.

**Comment by darkralts** [comment]
interesting, what about the pink screenshot on the main page here? looks like it was made using picom rules but if it works for you i can do that method if you want to share it

**Comment by sagb** [comment]
Screenshot is from here:
https://confluence.jaytaala.com/display/TKB/My+Manjaro+i3+setup#MyManjaroi3setup-Ricingalttab
Picom config is also there.

**Comment by darkralts** [comment]
![image](https://github.com/sagb/alttab/assets/16366107/b66cb868-d5d7-4714-baad-3e6a6cad68a1)
