### ISSUE TITLE
Bug Report ESC does not close the window cycle list

### ISSUE THREAD

**Issue by kurokawachan** [sagb/alttab#176]
#### set up environment
- With a virtual machine of Debian stable 12
- Install LXDE using
    ```
    # tasksel
    ```
    It would auto install openbox

- Disable the following section in default lxde-rc.xml
    ```
    ~/.config/openbox/lxde-rc.xml
    ```

    ```
        <!-- Keybindings for window switching -->
        <keybind key="A-Tab">
          <action name="NextWindow"/>
        </keybind>
        <keybind key="A-S-Tab">
          <action name="PreviousWindow"/>
        </keybind>
        <keybind key="C-A-Tab">
          <action name="NextWindow">
            <panels>yes</panels>
            <desktop>yes</desktop>
          </action>
        </keybind>


    ```
- You might need to reboot for the change to work
- launch alttab
#### steps
Press Alt+Tab without release alt, you would see the window cycle list
Press ESC while holding alt, you would see a next window in the list is focused
## What you would like to see
When press ESC, instead of a next window in the list is focused, the cycle list is closed

It is worthy of mentioning that, when holding the Alt key, using arrow key left or right would not select the window in the cycle list. The arrow key would be shown in the focused windows

**Comment by sagb** [comment]
Thank you for pointing this out.

**Comment by kurokawachan** [comment]
Hello @sagb , I am not sure if it would fix the issue. I used debugger and I didn't find this line been run

**Comment by sagb** [comment]
I've run it and it works for me: when I press Esc, the switcher disappears. Are you sure you run latest `master` branch code?

**Comment by sagb** [comment]
The behavior of `Esc` in `alttab` isn't dependent on the Linux distribution. To see changes immediately, checkout the latest `master` branch from github, build, and run the executable.

If you're waiting for Debian's official packages, you'll need to wait for the next release.

**Comment by kurokawachan** [comment]
Hello, I just found it is openbox key binding

I would have to disable the following line
```


  <keybind key="A-Escape">
    <action name="Lower"/>
    <action name="FocusToBottom"/> 
    <action name="Unfocus"/>
  </keybind>


```

Thanks! I really like this software
