### ISSUE TITLE
Non-English Characters (e.g., Cyrillic) Break When Using `-w 0` Option

### ISSUE THREAD

**Issue by trueTatar** [sagb/alttab#177]
When using `alttab` with the `-w 0` option to assume the absence of a window manager, the output of non-English characters (e.g., Cyrillic) in window titles becomes garbled. This issue occurs specifically when running on Debian 12.5 under GNOME. However, when running `alttab` without the `-w 0` option, everything works as expected, and Cyrillic characters are displayed correctly.

Steps to reproduce:
1. Run `alttab -w 0` on a system with windows that have non-English titles (e.g., Cyrillic).
2. Observe that non-English characters in the window titles are not displayed properly.

Environment:**
- **OS:** Debian 12.5  
- **Desktop Environment:** GNOME  
- **Alttab Version:** 1.6.1 (installed from `apt`)  
- **System Locale:** `en_US.UTF-8`

Screenshots attached (title window of `nautilus` inside the `Кириллические_символы` folder):
Garbled (with the `-w 0` option):
![garbled](https://github.com/user-attachments/assets/874d7070-792b-42f8-ab4f-cbf45690e38d)
Correct (without the `-w 0` option):
![correctly](https://github.com/user-attachments/assets/64cafe1b-6f6c-43c3-998f-a16122639c32)

**Comment by sagb** [comment]
Are you sure you need `-w 0`? It's a rather exotic mode, using tricks, meant for running in raw X11 environments where no sane window lists are available.

**Comment by sagb** [comment]
Should be fixed in `master`, can you try?

**Comment by trueTatar** [comment]
It works perfectly now! Thank you so much for your swift assistance.
