### ISSUE TITLE
In i3, error when selecting scratchpad window

### ISSUE THREAD

**Issue by eater** [sagb/alttab#45]
When a window is on a scratchpad in i3, it appears in the Alttab list, but selecting it gives the error "Unexpected X Error: BadMatch (invalid parameter attributes)".

**Comment by sagb** [comment]
Thank you for reporting!
I plan to fix this soon, together with other related issues (see #48).

**Comment by sagb** [comment]
This should be fixed in c5bb567, please test.
In `-d 0` (default) mode, scratchpad window should not appear in the switcher,
in `-d 1` it should appear and switching to it should be possible.

**Comment by eater** [comment]
This is working! But not _perfectly_.
`-d 0` is great. 
`-d 1` shows all the windows on every desktop, and 90% of the time, it successfully switches to the window I select, on any desktop. But 10% of the time, the current window flashes, but the focus does not change. I'm not sure how to reproduce that consistently. It seems to happen when I try to switch to a window on a different desktop. Looking at the -vv log when that happens, it says it's switching window but it does NOT say it's switching desktop:
```
Release 5600239: 9-50
destroying our window
changing focus to 7c00074
ewmh_setFocus 7c00074
ewmh switching window to 130023540
pull out g.winlist[0] to top
destroying tiles
destroying icons and winlist
sortlist before freeWinlist: 130023540 123731973 12646413 16777219 136314883 39845942 39846772 39846866 12759826 39845945 146800643 12847568 39846923 
```

**Comment by sagb** [comment]
Thank you for investigation, please pull and produce the sutiation again, I've added trivial verbosity in ewmh_setFocus (you can grep by "ewmh_setFocus")

**Comment by eater** [comment]
OK:
```
Press 2a9: 8-23
item 2
Release 56001a0: 8-23
destroying our window
changing focus to 2600374
ewmh_setFocus win 2600374
ewmh_setFocus fwin 0 opt 1 wdesk 0 cdesk 1
ewmh switching desktop to 0
ewmh switching window to 39846772
pull out g.winlist[2] to top
destroying tiles
destroying icons and winlist
sortlist before freeWinlist: 39846772 123731973 16777219 130023540 12646413 136314883 39845942 39846866 12759826 39845945 146800643 12847568 39846923 
```

**Comment by sagb** [comment]
There is a "switching desktop" message above. Didn't it actually switch the desktops?

**Comment by eater** [comment]
No, it didn't.

**Comment by sagb** [comment]
Please check if this temporary workaround fixes the problem.

**Comment by eater** [comment]
Yes, that works!

**Comment by sagb** [comment]
This is final resolution. Please reopen on inconsistent `-d` behaviour on i3 scratchpad window,
or file a new issue on inconsistent `-d` behaviour on other windows.
