### ISSUE TITLE
Focusing a window with mouse or keyboard commands should change MRU sort

### ISSUE THREAD

**Issue by eater** [sagb/alttab#51]
Alttab seems to only change the MRU sort order when a new window is focused *by Alttab*. 

1. With the focus in a terminal window, call it Window A, launch the Alttab application. `$ alttab -d 1`
2. With the mouse, click in another window, let's call it Window F.
3. With the mouse, click back to Window A. 
4. Invoke the Alttab switcher.
The sort order shown should now be A, F, B, C, D, etc. at this point, since Window F was recently used.  But instead it is A, B, C, D, E, F.

Ideally, Alttab would listen for all window focusing events in the window manager, and change its sort order every time a window is focused by any means.

**Comment by sagb** [comment]
This sounds reasonable, I'll think how to implement this.

**Comment by sagb** [comment]
Please test in i3.

**Comment by eater** [comment]
I'm not noticing any difference on i3 with the new commit.

**Comment by sagb** [comment]
I believe it's fixed, at least for i3.

**Comment by eater** [comment]
Confirmed. Fantastic!
