### ISSUE TITLE
Enhancement: make Alttab switcher clickable

### ISSUE THREAD

**Issue by eater** [sagb/alttab#52]
Especially when I have ~40 windows going, it would be a nice feature to be able to raise the switcher by hitting Alt-tab with my left hand, and then click on the correct option with the mouse in my right hand.

**Comment by sagb** [comment]
Is `-d 1` comfortable for you or you have to use `-d 1` just to see windows on i3 _scratchpad_?

**Comment by eater** [comment]
I definitely want my Alttab to show windows from all the workspaces. 

Incidentally, I think many i3 users would find it valuable to have a setting that shows windows from all workspaces EXCEPT scratchpads.

**Comment by sagb** [comment]
Mouse select implemented.
Also, use `-d 3` to avoid scratchpad windows.

**Comment by eater** [comment]
Working great!
