### ISSUE TITLE
Scroll with tile selection

### ISSUE THREAD

**Issue by cornerman** [sagb/alttab#54]
When having a lot of windows open (such that not all tiles fit into the visible part), the remaining windows are not displayed.

Pressing tab until reaching the right-most window, will not show the currently selected window. Can we scroll the tile when the selection goes out of the visible area?

**Comment by sagb** [comment]
When switcher doesn't fit the screen, alttab should decrease tile size proportionally. There was a small error in this calculation and it's fixed now, please pull the latest master branch and check.
Though I'm not quite sure I understood you correctly.

**Comment by cornerman** [comment]
Sorry for the misleading explanation - I have the current master running. Let me try to rephrase :)

When having a lot of window open and launching the alttab ui, not all window tiles fit into the switcher ui. The ui occupies about 60% of my screen and then just cuts off all remaining tiles. It does not seem to resize as it keeps my configured tile-size. Now when I press alt+tab a few times, I reach the right-most tile in the ui; pressing alt+tab again, then the next selected window is not visible as a tile - the ui does not show all available tiles.

**Comment by sagb** [comment]
Did you pull today's commit?

**Comment by cornerman** [comment]
yep, running dffc813

**Comment by sagb** [comment]
Please post the output of
`alttab [your options] -vv 2>&1 | egrep '^(tile|uiwin)'`
(you must show the switcher for debug lines to appear).

**Comment by cornerman** [comment]
With just a few window everthing is fine:
```
╰─➤ alttab -vv 2>&1 | egrep '^(tile|uiwin)'
tile w=64 h=64
uiwin 440x80 +0+0, 1 screen(s): [5120x1440]
```

Then with more windows:
```
tile w=64 h=64
uiwin 2168x80 +0+0, 1 screen(s): [5120x1440] 
```

It seems as if it thinks it is wider than it is?

**Comment by sagb** [comment]
Does "5120x1440" makes sense for you? Is your X configured for two 2560х monitors, but you expect alttab to appear on either of them only?

**Comment by cornerman** [comment]
The screen size is fine, I have two 1440p monitors, but the `uiwin` size reports a wrong width. When adding more window, the ui window starts growing until reaching circa half of the screen size.

```
tile w=64 h=64
uiwin 1232x80 +0+0, 1 screen(s): [5120x1440] 
tile w=64 h=64
uiwin 1304x80 +0+0, 1 screen(s): [5120x1440]
```

With the second uiwin log, the last tile is cut off.

**Comment by sagb** [comment]
Do you set non-default `-p` option?

**Comment by cornerman** [comment]
I had `none`, but now run alttab without any options. The behaviour is still the same. But with center one thing is different. As soon as it the ui has a width greater than half my screen, the ui moves from the middle of one screen to the middle of both screens. But it still cuts off remaining tiles.

**Comment by sagb** [comment]
It's not easy to understand such condition. Could you please
update to master HEAD,
open enough windows for the bug,
run alttab without any argument except of `-vv` (no -p please),
call the switcher at least once,
collect the stderr, possibly strip any private information from it
and post it here or somewhere or send to sa-dev AT rainbow POINT by.
Thank you.

**Comment by sagb** [comment]
Of course, I would prefer to reproduce this on my system, preferably without the need of two monitors. If you know how to do this, please let me know. Thanks for screenshots, btw.

**Comment by cornerman** [comment]
No worries, thanks for the fast responses! I will try it out later (with and without second monitor) and add the error logs. I am using i3 btw.

**Comment by eater** [comment]
I am trying to reproduce this on my i3 with `faed8b5`. I've never seen a tile visibly cut in half like that screenshot. When I have two monitors connected and I open the switcher on a portrait-oriented monitor with too many open windows, the switcher extends off both sides of the monitor, making some tiles not visible.
```
$ alttab -d 2 -vv 2>&1 | egrep '^(tile|uiwin)'        
tile w=112 h=128
uiwin 1928x144 +416+888, 1 screen(s): [2760x1920]
```

When the portrait-oriented monitor is the only monitor, and I restart Alttab, it scales properly.
```
$ alttab -d 2 -vv 2>&1 | egrep '^(tile|uiwin)'
tile w=55 h=62
uiwin 1079x78 +0+921, 1 screen(s): [1080x1920] 
```

**Comment by sagb** [comment]
> I am trying to reproduce this on my i3 with faed8b5. I've never seen a tile visibly cut in half like that screenshot. When I have two monitors connected and I open the switcher on a portrait-oriented monitor with too many open windows, the switcher extends off both sides of the monitor, making some tiles not visible.

> alttab -d 2 -vv 2>&1 | egrep '^(tile|uiwin)'        

Thank you, please show this first case as
`alttab -d 2 -vv 2>&1 | egrep '^(attr|tile|uiwin)'`

**Comment by eater** [comment]
``` alttab -d 2 -vv 2>&1 | egrep '^(attr|tile|uiwin)'
tile w=112 h=128
uiwin 968x144 +896+888, 1 screen(s): [2760x1920] 
attr x 0 y 0 width 968 height 144 border_width 0
```

**Comment by cornerman** [comment]
It behaves the same with one or two monitors.

With the new logging, I can see that the uiwin width is different from the xattributes width of the window if there are too many windows:

```
╰─➤ alttab -d 2 -vv 2>&1 | egrep '^(attr|tile|uiwin)'
tile w=64 h=64
uiwin 152x80 +0+0, 1 screen(s): [5120x1440] 
attr x 0 y 0 width 152 height 80 border_width 0
tile w=64 h=64
uiwin 1808x80 +0+0, 1 screen(s): [5120x1440] 
attr x 0 y 0 width 1280 height 80 border_width 0
```

**Comment by cornerman** [comment]
Here is a full error log of two runs. One with only two windows, one with many:

https://gist.github.com/cornerman/26d184ef9dbfcea78ec67e80a4eafe63

**Comment by cornerman** [comment]
Uh, I found the problem for cutting of the tiles. My i3 config somehow has a `floating_maximum_size 1280 x 1024`, which enforces a maximum width on this window :)

Thanks for the help!

Now, the window grows with more windows. With a lot of window it will now flow over the screen size. Can we do something about it? Like scrolling :)

**Comment by sagb** [comment]
That's good to hear)

Currently, when there are too much windows to fit the screen, alttab is meant to resize the tiles to fit everything. Perhaps scrolling of the entire switcher would look better than resize, but such a change requires an effort to implement, I need to think about this.

Also, for now, I don't want to bring a full-featured multi-monitor support, i.e. tracking the _current_ monitor in terms of WM. Instead, I've added a surrogate `-vp` option aimed for _dynamic_ positioning relative to _static_ user-defined rectangle, i.e. you can correctly position the switcher on _either_ of monitors, but not both) Probably this will change in the future, when I will have more time.

Don't close this bug yet, I'll add some minor enhancements later.

**Comment by sagb** [comment]
Just to clarify, the best current workaround for multimonitor configuration in i3 is probably `-vp WxH+0+0 -p none`, where WxH is the smallest size of any attached monitor.
Of course it's a mess and will be fixed later.

**Comment by sagb** [comment]
Users running i3 in multi-output configuration may be interested in changes introduced in e14f76b:
`-vp [focus|pointer]` to limit GUI viewport
`-sc` for selection windows by screen

**Comment by sagb** [comment]
At least, now it should not overflow the visible screens, and most of option combinations work as expected. Well, probably except of rare pain like @eater's rotated monitors.

**Comment by eater** [comment]
This is awesome. BRB, changing my username to @rarepain

**Comment by sagb** [comment]
I've just tested with rotated screens, and surprisingly, everything work smoothly)

**Comment by cornerman** [comment]
@sagb Thank you very much, `-vp focus -p center` works perfectly for me, now!

Though, I have noticed that with `-p none`, the window is sometime drawn in the center of the screen and sometimes rendered at the top of my screen (y = 0).
