### ISSUE TITLE
Rework -d and -sc syntax (was: allow excluding current workspace)

### ISSUE THREAD

**Issue by eater** [sagb/alttab#55]
With a tiling WM like i3, it's generally very easy to navigate to another window on the current workspace. Where a tool like Alttab is most useful is in rapidly switching to a window on a different workspace.

In using Alttab, I typically have to hit the key combo a few times to get past all the windows I've been focused on in the current workspace before I can select the one I want. Excluding every window from the current workspace would be a timesaver.

**Comment by sagb** [comment]
Let's clarify: when you run `alttab -d 1`, and switch from window A belonging to desktop D(A) to window B belonging to another desktop D(B), window A is left in the stack near window B, so you can switch back to A and vice versa in single Tab click? Does this work for you or, for some reason, no?
Anyway, I've added `-d 3` to exclude current desktop.

**Comment by eater** [comment]
Great: can you add an option to show **all desktops except current and scratchpad?**

(Would it be easier to keep track of these options as a string? For instance, `c` = current desktop, `o` = other normal desktops, and `s` = scratchpad (or "special"), so the user could call `alttab -d oc` instead of `-d 2`? Just an idea.)

In answer to your question, I commonly move around among a few windows on the current desktop using the mouse or i3 commands, and then when I want to alt-tab to the previously focused window on desktop, it's lower down in the stack.

**Comment by sagb** [comment]
This looks reasonable, I plan to rewrite options syntax at ~1.4 resease.
For now, I just make `-d 3` exclude special desktop too.
