### ISSUE TITLE
Enhancement: multiple invocation modes for single running instance

### ISSUE THREAD

**Issue by eater** [sagb/alttab#56]
Currently, I start Alttab with the `-d 2` switch to specify which workspaces I want it to handle, and that setting is set for the whole time Alttab runs. 

It might allow more flexibility if options like `-d 2`, `-d 0` etc. were not set in stone when the application starts, but each available depending on keystroke. For instance, `alt-tab` could be assigned to show a switcher of all desktops, `alt-~` would show a switcher of just the current desktop, another key combo to list just scratchpad windows, and so forth. 

That sort of configurability will become more useful if and when additional settings (for instance #55 ) are added to Alttab.

**Comment by sagb** [comment]
If I introduce this, the code would be nearly the same as running two separate alttab instances. Why don't you do this? The configuration described above is achieved with:
````
alttab -d 1 &
alttab -d 0 -kk 0x60 &
````

**Comment by eater** [comment]
Works for me! Thanks..
