### ISSUE TITLE
Enhancement: indicate window being selected

### ISSUE THREAD

**Issue by xzfc** [sagb/alttab#75]
E.g. openbox shows it as a black-and-white border ([screenshot](http://dump.bitcheese.net/files/cagalot/tmp.hh82OPGiqw)).

Some considerations:
* It should switch to corresponding desktop when `-d` is used.
* It should raise the window since using openbox-like border alone is not very indicative for stacked/tabbed layouts in tiled WMs (multiple windows layered on top of each other).

**Comment by sagb** [comment]
Sorry, these jumping borders and popping windows look so nasty that I believe it's not in the alttab simple style.
