### ISSUE TITLE
Enchancement: hjkl keys for selecting next/prev items in alttab switcher

### ISSUE THREAD

**Issue by jtaala** [sagb/alttab#88]
Would like to be able to define and use keys to select next/prev items in alttab switcher.
Namely "h" for selecting previous and "l" for selecting next.
To be clear, happy with hitting alt+tab for bring up switcher, but would like defining alternate keys to move selection.

Find this much faster than hitting tab (and shift+tab for reverse).

**Comment by sagb** [comment]
Since b01008b changes by @roboshim (#74) and @jtaala (#89) are merged in master.
For some test period, let's not grab extra keys by default, instead user must specify explicit options:
`-pk Left -nk Right`
or
`-pk H -nk L`

**Comment by jtaala** [comment]
Agree @sagb, many thanks - have moved over to your master and have been testing (no issues thus far!).
