### ISSUE TITLE
Fluxbox shows applets in alt+tab list

### ISSUE THREAD

**Issue by williamtwomey** [sagb/alttab#93]
alttab lists things like applets when launched from ~/.fluxbox/startup. For example, it shows nm-applet, mate-screensaver, etc. 

If I launch from alt+F2 (or just a terminal) after fluxbox starts it works normally without showing all these extraneous things. 

Just curious if anyone had some suggestions, or if this is a bug. 

Running latest Arch Linux, fluxbox 1.3.7

**Comment by williamtwomey** [comment]
Helps if I read the manual. Using -w 1 -d 1 resolved this.

**Comment by sagb** [comment]
Indeed, there was wrong instruction in alttab doc/wm-setup.md. ~/.fluxbox/startup is executed before fluxbox itself. To start application after fluxbox (to let alttab recognize everything), special shell construct is required: https://github.com/sagb/alttab/blob/master/doc/wm-setup.md#startup-5
