### ISSUE TITLE
How to use alt+tab and alt+shift+tab?

### ISSUE THREAD

**Issue by Harliff** [sagb/alttab#94]
I'm trying to set up forwad and backward switching (Alt+Tab for forward switching and Alt+Shift+Tab for backward switching). 

What I'm done wrong?

`alttab  -kk Tab -mk Alt_L -bk Shift_L`

**Comment by sagb** [comment]
You don't need to specify any option, these keys are default.
If they don't work, then probably another software such as window manager grabs those keys. See workarounds for specific window managers: https://github.com/sagb/alttab/blob/master/doc/wm-setup.md
